[build.environment]
LALA = "LULU"

[[edge_functions]]
path = "/hello"
function = "hello"

[[edge_functions]]
path = "/hello/*"
function = "hello"

[[edge_functions]]
path = "/admin"
function = "admin"

[[edge_functions]]
path = "/login"
function = "login"

[[edge_functions]]
path = "/error"
function = "error"

[[edge_functions]]
function = "env"
path = "/env"

[[plugins]]
package = "@netlify/netlify-plugin-functions-bundling-config"
