[build.environment]
LALA = "LULU"

[[edge_functions]]
path = "/hello"
function = "hello"

[[edge_functions]]
pattern = "^/hello/.*$"
function = "hello"
excludedPath = "/hello/nort"

[[edge_functions]]
path = "/login"
function = "login"

[[edge_functions]]
function = "env"
path = "/env"

[[plugins]]
package = "@netlify/netlify-plugin-functions-bundling-config"
